/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_sidechainTokens"
      | "_sidechainTokensByAddress"
      | "receiveByEthereumAssetAddress"
      | "receiveBySidechainAssetId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_sidechainTokens",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_sidechainTokensByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveByEthereumAssetAddress",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish[],
      BytesLike[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveBySidechainAssetId",
    values: [
      BytesLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish[],
      BytesLike[],
      BytesLike[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "_sidechainTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_sidechainTokensByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveByEthereumAssetAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveBySidechainAssetId",
    data: BytesLike
  ): Result;
}

export interface IBridge extends BaseContract {
  connect(runner?: ContractRunner | null): IBridge;
  waitForDeployment(): Promise<this>;

  interface: IBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _sidechainTokens: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  _sidechainTokensByAddress: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  receiveByEthereumAssetAddress: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      amount: BigNumberish,
      to: AddressLike,
      from: AddressLike,
      txHash: BytesLike,
      v: BigNumberish[],
      r: BytesLike[],
      s: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  receiveBySidechainAssetId: TypedContractMethod<
    [
      sidechainAssetId: BytesLike,
      amount: BigNumberish,
      to: AddressLike,
      from: AddressLike,
      txHash: BytesLike,
      v: BigNumberish[],
      r: BytesLike[],
      s: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_sidechainTokens"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "_sidechainTokensByAddress"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "receiveByEthereumAssetAddress"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      amount: BigNumberish,
      to: AddressLike,
      from: AddressLike,
      txHash: BytesLike,
      v: BigNumberish[],
      r: BytesLike[],
      s: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveBySidechainAssetId"
  ): TypedContractMethod<
    [
      sidechainAssetId: BytesLike,
      amount: BigNumberish,
      to: AddressLike,
      from: AddressLike,
      txHash: BytesLike,
      v: BigNumberish[],
      r: BytesLike[],
      s: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
