/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBridge } from "./IBridge";
export type { IBridgeWrapper } from "./IBridgeWrapper";
export type { IBridgeWrapperErrors } from "./IBridgeWrapperErrors";
